// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzeqarulccukfxkkevjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZXFhcnVsY2N1a2Z4a2tldmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDE4OTQsImV4cCI6MjA3NDQ3Nzg5NH0.uIlTKTmChgrqtEvLBmuCOpI5oUfIhF167TgQtbenfNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});